spring:
  application:
    name: stockexchange

  datasource:
    url: jdbc:mysql://mysql/stock_exchange?createDatabaseIfNotExist=true&useSSL=false&user=root
    username: root
    password: root

  # datasource:
  #   url: jdbc:mysql://localhost:3306/stock_exchange
  #   username: root
  #   password: 142002

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders : "*"

server:
  port: 8080
