apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: stock-exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mutedslow/stock-exchange-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_NAME
          value: stock_exchange
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD