apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: stock-exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mutedslow/stock-exchange-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "jdbc:mysql://db:3306/stock_exchange"  # Replace with the MySQL server address
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "stock_exchange"  # Replace with the database name
        - name: DB_USER
          value: "root"  # Replace with the username
        - name: DB_PASSWORD
          value: "142002"  # Replace with the password
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        imagePullPolicy: Always
      restartPolicy: Always
