apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boot-ingress
  namespace: stock-exchange
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Ensure React can handle all paths
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /?(.*)  # Catch all paths
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
