apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1URXlOREUwTURVME5sb1hEVE0wTVRFeU16RTBNRFUwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUY4CkUzdmlvTWgrVm9XL0hTUmJMbjlTc0RvdWpSa3JUQzVmdzBLT3RpcDlBd3ZtOWliOWQvZmUrbVpheUlXOUxXOHcKckt1ZFNCTmx3YnNVN1Ribm5mczdwd0wvQ1laSWdvbDhsNk1FblEwUmtjKzNrV0tTN0FQcHFlRFN2YjBFaEJBMgpZNVFFb01ycW9TT09wdVM2UWFrTDJlK2tQV1gxT1dGZzk5dVZCVEVlSk1ZbTgzK1BlQ2tQZlQrYUpIQUMralBUCmN2STlQSk0rTllMYjhxbDcxM0RWMVFGd3dWcU5MSHFRRzhUWi90UlVNOVRQTGFwV0VicTlUYTR5VmpPTWlvcGcKZjdNcWRidjJGM3E1ZHBaQ1VoVjJPZjFHeHAzSU1WbnZXS0xsZDdDejI3YnpYTjkyZ0lkMlpjVUU0TkFxaXJzegpQcGI2VEV3RXlmeVRoamVRaEs4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRcVc1bWRHNVpvNmF4ZVlFWHRnaTd3WldlUktUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKbkNOOStGbwprbDZEWXZZWjZ3VGxDa2hnYm1OS3dOUmdLcW5scCtvMTZKa3JJRjF4VHpuNElheUdEL3VoeTFvQ3B2czhLaDhICm1PSHpYc0NWMXlqeXV2eXRvdVNEMy9iWkNPd0gzWmxlTkZGb1hqblhZdThNbkhEay9ZVkNxT1BReVFDM1dvL0wKQ3VoOGZ0aE1vb1lydGt1czMrL3g5T21qM0VaalFwQ1dCckVxSGJRNjdaQSs1Mm9kSFhGUEU1dVNtVUZobmh1bgpCRytaeEhVaWlEcjc0eE1YYkdkYlRONjNDUVkxbFRlZWgrcVpwQitYVG1oRmYzZFVQWTdmaTZ0bUZwMmtza0dRCjhQaGZVdEw5QVM4ejk2ak5sWnJDb0QrU2M5TFdLcGo4dEFRRHNSOVFHcjdEQXc4ZUlDWUg3NWdMckkwbjF3VHIKaFowZDdlbXlLOEJBeFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.49.2:8443
  name: kubernetes
- cluster:
    certificate-authority: /home/sheikh/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 26 Nov 2024 08:09:45 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: kubernetes
    user: jenkins
  name: jenkins@kubernetes
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 26 Nov 2024 08:09:45 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlqNmJrRWw5UGNXcWlCMGJsVXdJVHhOUXNORG1HdFEwZ2ZTV21UMEkyM1kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzMyNTkwNzQxLCJpYXQiOjE3MzI1ODcxNDEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYmQ2NWNkYWYtNzM2Mi00NmM1LWE4YWQtMWIzOGQ2NDE3YjUyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiI0ZWQ4NTM1NS03NWFkLTRmNWEtODIzYy00MmQ3ZDQ0NjZiYjUifX0sIm5iZiI6MTczMjU4NzE0MSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6amVua2lucyJ9.GBTb3QkyycUcZmQI_y64n0pj0t1vXlj8lDr3RNDomlmDG0fJREC0UmFs8iaEwcK5HgGKoh20fBO6UWQ4FDHvvvHdWCNrxKQP9eCsfqei2IdC-1FKFuiinsrunKpAHpRZ_gfCiKShRDI_P_ERvXgLn_IK3Ic778nZU04KnbyBUarEYqJKa34LF5lwsin-Zj45KzEhwtvPo34ZMeiNuCUO4IRMj0VGKeO5SnaA-ReMIJwAZ6gVK7kyM49wBGOhh1Yr4J8I4C-CLVWjDYKH2_xXA6jmhrG2rQyL9dtzkHb76pWRiog8MiN6RbSookJQxv8h2Hl12kHSkYtAX8h_ywpqQ
- name: minikube
  user:
    client-certificate: /home/sheikh/.minikube/profiles/minikube/client.crt
    client-key: /home/sheikh/.minikube/profiles/minikube/client.key
