apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: stock-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        # - name: MYSQL_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: MYSQL_USER
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-sql-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-data
        emptyDir: {}
      - name: init-sql-scripts
        configMap:
          name: mysql-init-script
