apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: stock-exchange
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30009
  type: NodePort