apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: stock-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.0
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://192.168.49.2:30009
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: stock-exchange
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer
