apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: stock-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.10.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: logstash-pipeline-volume
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-pipeline