apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: stock-exchange
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      json {
        source => "message"
      }
    }
    output {
      elasticsearch {
        hosts => ["http://192.168.49.2:30009"]
        index => "application-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }