kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: stock-exchange
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None