---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install prerequisites system-wide
      shell: |
        python3.12 -m pip install --break-system-packages openshift pyyaml kubernetes
      args:
        executable: /bin/bash

    - name: Deploy ElasticSearch
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/elasticsearch-deployment.yaml') | from_yaml }}"

    - name: Create ElasticSearch Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/elasticsearch-service.yaml') | from_yaml }}" 

    - name: Pause for 20 seconds
      pause:
        seconds: 20  

    - name: Create Logstash Config
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/logstash-configmap.yaml') | from_yaml }}"

    - name: Deploy Logstash
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/logstash-deployment.yaml') | from_yaml }}"

    - name: Create Logstash Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/logstash-service.yaml') | from_yaml }}"

    - name: Pause for 10 seconds
      pause:
        seconds: 10

    - name: Deploy Kibana
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/kibana-deployment.yaml') | from_yaml }}"

    - name: Create Kibana Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../elk/kibana-service.yaml') | from_yaml }}"

