---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install prerequisites system-wide
      shell: |
        python3.12 -m pip install --break-system-packages openshift pyyaml kubernetes
      args:
        executable: /bin/bash

    - name: Deploy MySQL
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/mysql-deployment.yaml') | from_yaml }}"

    - name: Create MySQL Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/mysql-service.yaml') | from_yaml }}"


    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/boot-backend-secret.yaml') | from_yaml }}"
        
      

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-deployment.yaml') | from_yaml }}"
        
      

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-service.yaml') | from_yaml }}"
        
      

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/backend-deployment.yaml') | from_yaml }}"
        
      

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/backend-service.yaml') | from_yaml }}"
        
      

    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-configmap.yaml') | from_yaml }}"

    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/mysql-configmap.yaml') | from_yaml }}"
        
    - name: Create Config
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/mysql-config.yaml') | from_yaml }}"   

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/boot-ingress.yaml') | from_yaml }}"
        
      
