---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure pipx is installed
      apt:
        name: pipx
        state: present

    - name: Ensure pipx binary is available
      shell: |
        export PATH=$PATH:/usr/local/bin
        echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc
      args:
        executable: /bin/bash

    - name: Install openshift using pipx
      shell: |
        pipx install openshift || pipx upgrade openshift
      args:
        executable: /bin/bash

    - name: Install pyyaml using pipx
      shell: |
        pipx install pyyaml || pipx upgrade pyyaml
      args:
        executable: /bin/bash

    - name: Install kubernetes using pipx
      shell: |
        pipx install kubernetes || pipx upgrade kubernetes
      args:
        executable: /bin/bash

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/boot-backend-secret.yaml') | from_yaml }}"

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-deployment.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-service.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-service.yaml') | from_yaml }}"

    - name: Create ConfigMap
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-configmap.yaml') | from_yaml }}"

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/boot-ingress.yaml') | from_yaml }}"
