---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install prerequisites system-wide
      shell: |
        python3 -m pip install --break-system-packages openshift pyyaml kubernetes
      args:
        executable: /bin/bash

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/boot-backend-secret.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-deployment.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-service.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/backend-deployment.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/backend-service.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/frontend-configmap.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/boot-ingress.yaml') | from_yaml }}"
        kubeconfig: "/var/lib/jenkins/.kube/config"
      
