---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure Python3 and virtualenv are installed
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
        state: present

    - name: Create a virtual environment for Ansible Kubernetes modules
      command: python3 -m venv /opt/ansible-venv
      args:
        creates: /opt/ansible-venv/bin/activate

    - name: Install required Python packages in the virtual environment
      shell: |
        source /opt/ansible-venv/bin/activate && pip install openshift pyyaml kubernetes
      args:
        executable: /bin/bash

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/boot-backend-secret.yaml') | from_yaml }}"

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-deployment.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-service.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-service.yaml') | from_yaml }}"

    - name: Create ConfigMap
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-configmap.yaml') | from_yaml }}"

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/boot-ingress.yaml') | from_yaml }}"
